### ISSUE TITLE
Support x32/386 architecture in ndr

### ISSUE THREAD

**Issue by nsemikov** [oiweiwei/go-msrpc#13]
Greetings!

I got an error when trying to compile on 386 archutecture:
```Bash
# github.com/oiweiwei/go-msrpc/ndr
vendor/github.com/oiweiwei/go-msrpc/ndr/buffer.go:392:9: cannot use (1 << 31) (untyped int constant 2147483648) as int value in return statement (overflows)
```

**Comment by oiweiwei** [comment]
Hello, @nsemikov. Could you please check with latest commit? https://github.com/oiweiwei/go-msrpc/commit/6258a861e43bb7150e4470434694b852c502a891

**Comment by nsemikov** [comment]
Thanks! It works for me.
When is the patch with the fix expected?

**Comment by oiweiwei** [comment]
well, I can release it now as I don't have any schedule :)
