### ISSUE TITLE
 Can you consider more protocol example implementations?

### ISSUE THREAD

**Issue by cd-senwang-tech** [oiweiwei/go-msrpc#19]
There are still many protocol implementations that have not yet been written, such as MS-TSCH.

**Comment by oiweiwei** [comment]
Could you please describe what would be a practical example in such case, because I cannot go through every MSDN paper to make up an example for every RPC endpoint? Mostly all the libs are enriched with documentation from MSDN portal so it seems to be relatively straight-forward to adapt existing examples with help of methods' documentation.

**Comment by cd-senwang-tech** [comment]
```golang
package main

import (
	"context"
	"fmt"
	"github.com/oiweiwei/go-msrpc/dcerpc"
	"github.com/oiweiwei/go-msrpc/msrpc/sch/itaskschedulerservice/v1"
	"github.com/oiweiwei/go-msrpc/ssp"
	"github.com/oiweiwei/go-msrpc/ssp/credential"
	"github.com/oiweiwei/go-msrpc/ssp/gssapi"
	"os"

	_ "github.com/oiweiwei/go-msrpc/msrpc/erref/win32"
)

func init() {
	// add credentials.
	gssapi.AddCredential(credential.NewFromPassword(os.Getenv("USERNAME"), os.Getenv("PASSWORD")))
	// add mechanism.
	gssapi.AddMechanism(ssp.SPNEGO)
	gssapi.AddMechanism(ssp.NTLM)
}

func main() {
	ctx := gssapi.NewSecurityContext(context.Background())

	cc, err := dcerpc.Dial(ctx, "localhost", dcerpc.WithEndpoint("ncacn_np:[atsvc]"))
	if err != nil {
		fmt.Println("Dial err:", err)
		os.Exit(1)
	}
	cli, err := itaskschedulerservice.NewTaskSchedulerServiceClient(ctx, cc, dcerpc.WithInsecure())
	if err != nil {
		fmt.Fprintln(os.Stderr, "cli", err)
		os.Exit(1)
	}
	println(cli)
	//cli.RegisterTask(ctx)
}

```

**Comment by cd-senwang-tech** [comment]
How to call the MS-TSCH protocol correctly? I didn’t expect the reply to be so fast LOL

**Comment by oiweiwei** [comment]
Is there any error in the sample above?

**Comment by cd-senwang-tech** [comment]
cli bind: could not bind the selected transport: ncacn_np: open smb session: response error: Indicates a referenced user name and authentication information are valid, but some user account restriction has prevented successful authentication (such as time-of-day restrictions).

**Comment by cd-senwang-tech** [comment]
Because I want to use the current credentials for authentication, so I don’t need to enter the username and password.

**Comment by cd-senwang-tech** [comment]
For example, this project is the same https://github.com/Rvn0xsy/SchtaskCreator/blob/master/SchtaskCreator.cpp

**Comment by oiweiwei** [comment]
@cd-senwang-tech I checked the example above and what can I conclude. On my system, using Admin credentials it works. It also requires WithSeal() instead of WithInsecure(). However, in your case, the failure is due to your system restrictions that does not allow to connect to ATSvc pipe remotely (yeah, using RPC is a remote connection eventhough you're connecting to the localhost as it still goes through the network stack)

**Comment by oiweiwei** [comment]
I recommend to look into exact restriction error you see and find a workaround suitable for your setup: https://www.easy365manager.com/a-user-account-restriction-is-preventing-you-from-logging-on/

**Comment by cd-senwang-tech** [comment]
I think i should use ncalrpc

**Comment by cd-senwang-tech** [comment]
When the Protocol sequence is ncalrpc, there is no need to provide user credentials.

**Comment by oiweiwei** [comment]
You can also consider checking USERNAME / PASSWORD env values. Perhaps they are empty and you are attempting to log in anonymously.

Note, these env variables are constants and must be defined by you (so you will have to pass them to your program)

As the library implements remote and platform independent part of the MSRPC there is no way for library to know credentials if do not type them in (that is, program have no idea about "current user").

**Comment by oiweiwei** [comment]
Correct, ncalrpc is the only way in such case, but this cannot be supported by this lib (as this is win32 specific interaction with windows kernel and not with network)

**Comment by cd-senwang-tech** [comment]
ref.(that is, program have no idea about "current user"). So i must Input  credentials Tks.

**Comment by cd-senwang-tech** [comment]
Ok, Thank you for your prompt reply

**Comment by oiweiwei** [comment]
Closing the issue then.
