### ISSUE TITLE
Wrong length of  CommonHeaderLength and no multiplicity check 8

### ISSUE THREAD

**Issue by dodgyturtle** [oiweiwei/go-msrpc#7]
Samba rise  several errors in logs:
1. https://github.com/oiweiwei/go-msrpc/blob/f3e83774419d72e720862e8bee27eb86e9408765/ndr/ndr_type_serialization_v1.go#L107 -> default length of CommonHeaderLength is 16, but Samba wants 8.
2. https://github.com/oiweiwei/go-msrpc/blob/f3e83774419d72e720862e8bee27eb86e9408765/ndr/ndr_type_serialization_v1.go#L120 -> Sometimes length of ObjectBufferLength not multiple of 8. I think, you need to add check as in marshalling of PAC.

Thanks! :)

**Comment by oiweiwei** [comment]
@dodgyturtle right, thanks! fixed now.
