### ISSUE TITLE
Add marshalling and unmarshalling PAC_REQUESTOR_SID and PAC_REQUESTOR_GUID

### ISSUE THREAD

**Issue by dodgyturtle** [oiweiwei/go-msrpc#9]
Hello!

Can you please add PAC PAC_REQUESTOR_SID and PAC_REQUESTOR_GUID type to PAC?

PAC_REQUESTOR_SID: https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-pac/c34adc61-80e1-4920-8923-22ef5054c4b2
PAC_REQUESTOR_GUID: https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-pac/28b694b8-affd-4b41-8769-6cfb2d3fde59

Thanks!

**Comment by oiweiwei** [comment]
@dodgyturtle could you please check with this change (https://github.com/oiweiwei/go-msrpc/commit/b11b4de73b0201b32523d1a46a76f4fd0ad573ba), I'm not sure about the format of the marshaled data as I couldn't find any samples.

**Comment by dodgyturtle** [comment]
Thank's. All great!
